-- =====================================================================
-- Data-Health · 01 · Esquema (tablas)
-- Ejecutar conectado como DATAHEALTH (el usuario creado en el script 00).
-- Ejecutar con "Ejecutar script" (F5).
--
-- La app usa spring.jpa.hibernate.ddl-auto=validate: Hibernate NO crea tablas,
-- solo comprueba que existan y coincidan con las entidades Java.
-- Cubre las entidades actuales: Eps, Usuario, RegistroAuditoria.
-- =====================================================================

-- ---------- EPS (entidad Eps) ----------
CREATE TABLE eps (
  id_eps  NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
  nombre  VARCHAR2(255 CHAR) NOT NULL,
  activa  NUMBER(1)          DEFAULT 1 NOT NULL,
  CONSTRAINT pk_eps        PRIMARY KEY (id_eps),
  CONSTRAINT uq_eps_nombre UNIQUE (nombre),
  CONSTRAINT ck_eps_activa CHECK (activa IN (0, 1))
);

-- ---------- USUARIO (entidad Usuario) ----------
CREATE TABLE usuario (
  id_usuario        NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
  id_eps            NUMBER(19)         NOT NULL,
  nombre            VARCHAR2(255 CHAR) NOT NULL,
  email             VARCHAR2(255 CHAR) NOT NULL,
  password_hash     VARCHAR2(255 CHAR) NOT NULL,
  rol               VARCHAR2(255 CHAR) NOT NULL,
  activo            NUMBER(1)          DEFAULT 1 NOT NULL,
  intentos_fallidos NUMBER(10)         DEFAULT 0 NOT NULL,
  bloqueado_hasta   TIMESTAMP(6),
  creado_por        NUMBER(19),
  fecha_creacion    TIMESTAMP(6)       NOT NULL,
  CONSTRAINT pk_usuario        PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_email  UNIQUE (email),
  CONSTRAINT fk_usuario_eps    FOREIGN KEY (id_eps) REFERENCES eps (id_eps),
  CONSTRAINT ck_usuario_activo CHECK (activo IN (0, 1)),
  CONSTRAINT ck_usuario_rol    CHECK (rol IN ('ADMIN_ENTIDAD','PERSONAL_MEDICO','PERSONAL_ADMINISTRATIVO','PACIENTE','CUIDADOR'))
);

-- ADR-03: toda consulta filtra por id_eps, así que se indexa.
CREATE INDEX idx_usuario_eps ON usuario (id_eps);

-- ---------- REGISTRO_AUDITORIA (entidad RegistroAuditoria, ADR-06) ----------
-- id_eps es opcional a propósito: un intento de login con un correo inexistente no tiene EPS.
CREATE TABLE registro_auditoria (
  id_auditoria NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
  id_eps       NUMBER(19),
  usuario      VARCHAR2(255 CHAR),
  accion       VARCHAR2(255 CHAR) NOT NULL,
  detalle      VARCHAR2(255 CHAR),
  fecha_hora   TIMESTAMP(6)       NOT NULL,
  CONSTRAINT pk_registro_auditoria PRIMARY KEY (id_auditoria)
);

CREATE INDEX idx_auditoria_eps   ON registro_auditoria (id_eps);
CREATE INDEX idx_auditoria_fecha ON registro_auditoria (fecha_hora);

-- Auditoría de solo inserción (ADR-06): nadie puede modificar ni borrar registros.
CREATE OR REPLACE TRIGGER trg_auditoria_solo_insercion
BEFORE UPDATE OR DELETE ON registro_auditoria
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'registro_auditoria es de solo insercion');
END;
/
