spring.application.name=datahealth
spring.profiles.active=dev

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=60
app.security.max-failed-attempts=3
app.security.lock-minutes=15
app.cors.allowed-origin=http://localhost:4200
app.seed.admin-email=admin@demo.com
app.seed.admin-password=Admin12345*
